### ISSUE TITLE
Make the website responsive.

### ISSUE THREAD

**Issue by stephin007** [stephin007/photography_portfolio#1]
Anyone reading this, Its a great project for beginners to work with, its on basic html, css etc. All you have to do is install the live  server extension to run it locally.
Otherwise just open the html file and open it on Chrome/🔥 🦊/ Safari etc.

The website is live as well if you wanna check it!
Please do leave a 🌟 to the Repo if you like it.

**Comment by sambatlim** [comment]
I want to work on this.
Could you assign me?

**Comment by stephin007** [comment]
Sure @sambatlim , Please go ahead

**Comment by sambatlim** [comment]
Could you provide more detail on this issue? Which part that it is not responsive?

**Comment by stephin007** [comment]
> Could you provide more detail on this issue? Which part that it is not responsive?

Hey @sambatlim specifically the gallery section, basically the whole responsive system is kind of in a very brittle situation. It would eb great if you check the responsiveness of the whole site!

**Comment by sambatlim** [comment]
can i modify some of your front end such as font size and layout?

**Comment by stephin007** [comment]
> can i modify some of your front end such as font size and layout?

Sure! NO issues @sambatlim

**Comment by Amulya-coder** [comment]
@stephin007 Can I also contribute .I wants to work on it.

**Comment by trivedidhruvil9** [comment]
Hey, you want any other changes in your front end ??

it's a really good build and i would love to contribute.

**Comment by Amulya-coder** [comment]
@stephin007 I can apply the Awesome Fonts and modify the About me section so that it looks good.

**Comment by stephin007** [comment]
> Hey, you want any other changes in your front end ??
> 
> it's a really good build and i would love to contribute.

Hey @trivedidhruvil9 , Please do changes as you wish.

**Comment by stephin007** [comment]
> @stephin007 I can apply the Awesome Fonts and modify the About me section so that it looks good. 

Hey @Amulya-coder please do the changes as you wish.

**Comment by sambatlim** [comment]
Guy I will work in gallery section.

**Comment by stephin007** [comment]
Yes, @sambatlim please continue

**Comment by sambatlim** [comment]
> Yes, @sambatlim please continue

I have finished and make PR for responsive gallery layout.

**Comment by Amulya-coder** [comment]
@stephin007 Changes have been made. Please review it. Thanks
